services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"
    environment:
        MYSQL_DATABASE: db_investimento
        MYSQL_USER: springuser
        MYSQL_PASSWORD: 12345
        MYSQL_ROOT_PASSWORD: root
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"